config/routes.rb
Rails.application.routes.draw do
  root "root#index"
  resources :skills
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
    validates :name, presence: true, length: { minimum: 1}
    validates :grading, presence: true, numericality: { other_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/root_controller.rb
class RootController < ApplicationController
    def index
    end
  end
  

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end
  
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
      if @skill.save
        redirect_to @skill
      else
        render :new
      end
    end
  def edit
        @skill = Skill.find(params[:id])
      end
    
  def update
        @skill = Skill.find(params[:id])
    
        if @skill.update(skill_params)
          redirect_to @skill
        else
          render :edit
        end
      end
 def destroy
        @skill = Skill.find(params[:id])
        @skill.destroy
    
        redirect_to root_path
      end
    
  private
    def skill_params
        params.require(:skill).permit(:name, :grading)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MvcExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<!DOCTYPE html>
<head>
 <meta title="first steps on rails"/>
</head>
<p>My custom landing page</p>
<body></body>
</html>

app/views/skills/_form.html.erb
<%= form_with model: @skill do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
    <% @skill.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %><br>
  </div>

  <div>
    <%= form.label :grading %><br>
    <%= form.number_field :grading %><br>
    <% @skill.errors.full_messages_for(:grading).each do |message| %>
        <div><%= message %></div>
      <% end %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Edit Skill</h1>
<%= render "form", skill: @skill %>

app/views/skills/index.html.erb
<h1>Skills</h1>
<p>List of skills and a attempt at objective self evaluation</p>
<table>
    <tr>
        <th>Skill</th>
        <th>Grading</th>
    </tr>
    <% @skills.each do | skill | %>
    <tr>
        <td>
         <%= link_to skill.name, skill %>
         </td>
         <td>
         <%= skill.grading %>
         </td>
    </tr>
    <% end %>
</table>
<%= link_to "New Skill", new_skill_path %>

app/views/skills/new.html.erb
<h1>Adding a new skill</h1>
<%= render "form", skill: @skill %>

app/views/skills/show.html.erb
<h1> You chose <%= @skill.name  %> </h1>
<h2> The grading is: <%= @skill.grading %> </h2>
<ul>
  <li><%= link_to "Edit", edit_skill_path(@skill) %></li>
    <li><%= link_to "Destroy", skill_path(@skill),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>